export function DownloadButton({ messages, feedbackHistory, company, role, caseLabel }) {
  function buildTranscript() {
    const lines = []
    const date  = new Date().toLocaleString()
    const sep   = "=".repeat(60)
    const div   = "-".repeat(60)

    lines.push(sep, "CASEGYM — SESSION TRANSCRIPT & ASSESSMENT", sep)
    lines.push(`Date:    ${date}`)
    lines.push(`Company: ${company}`)
    lines.push(`Case:    ${caseLabel}`)
    lines.push(`Role:    ${role}`)
    lines.push("")

    lines.push(div, "CONVERSATION TRANSCRIPT", div)
    messages.forEach((msg, i) => {
      lines.push(`\n[${i + 1}] ${msg.role === 'user' ? 'YOU' : msg.speaker || 'INTERVIEWER'}:`)
      lines.push(msg.text)
    })

    const valid = (feedbackHistory || []).filter(Boolean)
    if (valid.length > 0) {
      lines.push("", div, "PER-TURN ASSESSMENT", div)
      valid.forEach((fb, i) => {
        lines.push(`\nTURN ${i + 1}  —  Overall: ${fb.overall_score}/10`)
        if (fb.scores) {
          Object.entries(fb.scores).forEach(([k, v]) => {
            lines.push(`  ${k.replace(/_/g,' ')}: ${v.score}/10 — ${v.explanation}`)
          })
        }
        if (fb.strengths?.filter(Boolean).length > 0) {
          lines.push("\nStrengths:")
          fb.strengths.filter(Boolean).forEach(s => lines.push(`  + ${s}`))
        }
        if (fb.areas_of_improvement?.filter(Boolean).length > 0) {
          lines.push("\nAreas to improve:")
          fb.areas_of_improvement.filter(Boolean).forEach(a => lines.push(`  △ ${a}`))
        }
        if (fb.top_1_percent_response) {
          lines.push(`\nTop 1% response:\n  "${fb.top_1_percent_response}"`)
        }
        if (fb.actionable_next_steps?.length > 0) {
          lines.push("\nNext steps:")
          fb.actionable_next_steps.forEach(s => lines.push(`  → ${s}`))
        }
      })

      const avg = (valid.reduce((s, f) => s + f.overall_score, 0) / valid.length).toFixed(1)
      lines.push("", div, "SESSION SUMMARY", div)
      lines.push(`Turns completed: ${valid.length}`)
      lines.push(`Average score:   ${avg}/10`)

      const allSteps = valid.flatMap(f => f.actionable_next_steps || []).filter(Boolean)
      if (allSteps.length > 0) {
        lines.push("\nKey areas to work on:")
        ;[...new Set(allSteps)].slice(0, 5).forEach(s => lines.push(`  → ${s}`))
      }
    }

    lines.push("", sep, "Generated by CaseGym", sep)
    return lines.join("\n")
  }

  function handleDownload() {
    const blob = new Blob([buildTranscript()], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `casegym_${(company || 'session').toLowerCase().replace(/\s/g,'_')}_${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <button onClick={handleDownload}
      className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-xl text-xs font-medium text-gray-600 hover:bg-gray-50 transition-all">
      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5}
          d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/>
      </svg>
      Download transcript
    </button>
  )
}